<h1>C++ exceptions under the hood 3: an ABI to appease the linker<a name="cexceptionsunderthehood3anabitoappeasethelinker"></a></h1>
<p>On our journey to understand exceptions we discovered that the heavy-lifting is done in libstdc++ as specified by the C++ ABI. Reading some linker errors we deduced last time that for handling exceptions we need help from the C++ ABI; we created a throwing C++ program, linked it together with a plain C program and found that the compiler somehow translated our throw instruction into something that is now calling a few libstd++ functions to actually throw an exception. Lost already? You can check the sourcode for this project so far <a href="https://github.com/nicolasbrailo/cpp_exception_handling_abi/tree/master/abi_v01">in my github repo</a>.</p>
<p>Anyway, we want to understand exactly how an exception is thrown, so we will try to implement our own mini-ABI, capable of throwing an exception. To do this, a lot of <a href="/blog/youfoundadeadlink.html">RTFM</a> is needed, but a full ABI interface can be found <a href="http://libcxxabi.llvm.org/spec.html">here, for LLVM</a>. Let&rsquo;s start by remembering what those missing functions are:</p>
<pre lang="c++" style="display: inline-block; border: 1px solid red;">&amp;gt; gcc main.o throw.o -o app
throw.o: In function <code>foo()&amp;amp;#x27;:
throw.cpp:4: undefined reference to
</code>__cxa_allocate_exception&amp;#x27;
throw.cpp:4: undefined reference to <code>__cxa_throw&amp;amp;#x27;
throw.o:(.rodata._ZTI9Exception[typeinfo for Exception]+0x0): undefined reference to</code>vtable for __cxxabiv1::__class_type_info&amp;#x27;
collect2: ld returned 1 exit status
</pre>
<h3>__cxa_allocate_exception<a name="__cxa_allocate_exception"></a></h3>
<p>The name is quite self explanatory, I guess. <strong>__cxa_allocate_exception</strong> receives a size_t and allocates enough memory to hold the exception being thrown. There is more to this that what you would expect: when an exception is being thrown some magic will be happening with the stack, so allocating stuff here is not a good idea. Allocating memory on the heap might also not be a good idea, though, because we might have to throw if we&rsquo;re out of memory. A static allocation is also not a good idea, since we need this to be thread safe (otherwise two throwing threads at the same time would equal disaster). Given these constraints, most implementations seem to allocate memory on a local thread storage (heap) but resort to an emergency storage (presumably static) if out of memory. We, of course, don&rsquo;t want to worry about the ugly details so we can just have a static buffer if we want to.</p>
<h3>__cxa_throw<a name="__cxa_throw"></a></h3>
<p>The function doing all the throw-magic! According to the ABI reference, once the exception has been created <strong>__cxa_throw</strong> will be called. This function will be responsible of starting the stack unwinding. An important effect of this: <strong>__cxa_throw</strong> is never supposed to return. It either delegates execution to the correct catch block to handle the exception or calls (by default) <strong>std::terminate</strong>, but it never ever returns.</p>
<h3>vtable for __cxxabiv1::__class_type_info<a name="vtablefor__cxxabiv1__class_type_info"></a></h3>
<p>A weird one&hellip; __class_type_info is clearly some sort of RTTI, but what exactly? It&rsquo;s not easy to answer this one now and it&rsquo;s not terribly important for our mini ABI; we&rsquo;ll leave it to an appendix for after we are done analyzing the process of throwing exceptions, for now let&rsquo;s just say this is the entry point the ABI defines to know (in runtime) whether two types are the same or not. This is the function that gets called to determine whether a catch(Parent) can handle a throw Child. For now we&rsquo;ll focus on the basics: we need to give it an address for the linker (ie defining it won&rsquo;t be enough, we need to instantiate it) and it has to have a vtable (that is, it must have a virtual method).</p>
<p>Lot&rsquo;s of stuff happen on these functions, but let&rsquo;s try to implement the simplest exception thrower possible: one that will call exit when an exception is thrown. Our application was almost OK but missing some ABI-stuff, so let&rsquo;s create a mycppabi.cpp. Reading <a href="/blog/youfoundadeadlink.html">our ABI specification</a> we can figure out the signatures for <strong>__cxa_allocate_exception</strong> and <strong>__cxa_throw</strong>:</p>
<pre lang="c++" style="display: inline-block; border: 1px solid red;">#include &amp;lt;unistd.h&amp;gt;
#include &amp;lt;stdio.h&amp;gt;
#include &amp;lt;stdlib.h&amp;gt;
namespace __cxxabiv1 {
    struct __class_type_info {
        virtual void foo() {}
    } ti;
}
#define EXCEPTION_BUFF_SIZE 255
char exception_buff[EXCEPTION_BUFF_SIZE];
extern &quot;C&quot; {
void<em> __cxa_allocate_exception(size_t thrown_size)
{
    printf(&quot;alloc ex %i\n&quot;, thrown_size);
    if (thrown_size &amp;gt; EXCEPTION_BUFF_SIZE) printf(&quot;Exception too big&quot;);
    return &amp;amp;exception_buff;
}
void __cxa_free_exception(void </em>thrown_exception);
#include &amp;lt;unwind.h&amp;gt;
void __cxa_throw(
          void<em> thrown_exception,
          struct type_info </em>tinfo,
          void (<em>dest)(void</em>))
{
    printf(&quot;throw\n&quot;);
    // __cxa_throw never returns
    exit(0);
}
} // extern &quot;C&quot;
</pre>
<p>Note: You can download the full sourcecode for this project <a href="https://github.com/nicolasbrailo/cpp_exception_handling_abi/tree/master/abi_v01">in my github repo</a>.</p>
<p>If we now compile mycppabi.cpp and link it with the other two .o files, we&rsquo;ll get a working binary which should print &ldquo;alloc ex 1\nthrow&rdquo; and then exit. Pretty simple, but an amazing feat nonetheless: we&rsquo;ve managed to throw an exception without calling libc++. We&rsquo;ve written a (very small) part of a C++ ABI!</p>
<p>Another important bit of wisdom we gained by creating our own mini ABI: the throw keyword is compiled into two function calls to libstdc++. No voodoo there, it&rsquo;s actually a pretty simple transformation. We can even disassemble our throwing function to verify it. Let&rsquo;s run this command &ldquo;g++ -S throw.cpp&rdquo;.</p>
<pre lang="c++" style="display: inline-block; border: 1px solid red;">seppuku:
.LFB3:
    [&hellip;]
    call    __cxa_allocate_exception
    movl    $0, 8(%esp)
    movl    $_ZTI9Exception, 4(%esp)
    movl    %eax, (%esp)
    call    __cxa_throw
    [&hellip;]
</pre>
<p>Even more magic happening: when the throw keyword gets translated into these two calls, the compiler doesn&rsquo;t even know how the exception is going to be handled. Since libstdc++ is the one defining __cxa_throw and friends, and libstdc++ is dynamically linked on runtime, the exception handling method could be chosen when we first run our executable.</p>
<p>We are now seeing some progress but we still have a long way to go. Our ABI can only throw exceptions right now. Can we extend it to handle a catch as well? We&rsquo;ll see how next time.</p>