<h1>C++ exceptions under the hood 8: two-phase handling<a name="cexceptionsunderthehood8twophasehandling"></a></h1>
<p>We finished last chapter on the series about C++ exceptions by adding a personality function that _Unwind_ was able to call. It didn&rsquo;t do much but there it was. The ABI we have been implementing can now throw exceptions and the catch is already halfway implemented, but the personality function needed to properly choose the catch block (landing pad) is bit dumb so far. Let&rsquo;s start this new chapter by trying to understand what are the parameters that the personality function receives and next time we&rsquo;ll begin adding some real behavior to __gxx_personality_v0: when __gxx_personality_v0 is called we should say &ldquo;yes, this stack frame can indeed handle this exception&rdquo;.</p>
<p>We already said we won&rsquo;t care for the version or the exceptionClass for our mini ABI. Let&rsquo;s ignore the context too, for now: we&rsquo;ll just handle every exception with the first stack frame above the function throwing; note this implies there must be a try/catch block on the function immediately above the throwing function, otherwise everything will break. This also implies the catch will ignore its exception specification, effectively turning it into a catch(&hellip;). How do we let _Unwind_ know we want to handle the current exception?</p>
<p>_Unwind_Reason_Code is the return value from the personality functions; this tells _Unwind_ whether we found a landing pad to handle the exception or not. Let&rsquo;s implement our personality function to return _URC_HANDLER_FOUND then, and see what happens:</p>
<pre lang="c++" style="display: inline-block; border: 1px solid red;">alloc ex 1
__cxa_throw called
Personality function FTW
Personality function FTW
no one handled __cxa_throw, terminate!
</pre>
<p>See that? We told _Unwind_ we found a handler, and it called the personality function yet again! What is going on there?</p>
<p>Remember the action parameter? That&rsquo;s how _Unwind_ tells us what he is expecting, and that is because the exception catching is handled in two phases: lookup and cleanup (or _UA_SEARCH_PHASE and _UA_CLEANUP_PHASE). Let&rsquo;s go again over our exception throwing and catching recipe:</p>
<ul>
<li>__cxa_throw/__cxa_allocate_exception will create an exception and forward it to a lower-level unwind library by calling _Unwind_RaiseException</li>
<li>Unwind will use CFI to know which functions are on the stack (ie to know how to start the stack unwinding)</li>
<li>Each function has have an LSDA (language specific data area) part, added into something called &ldquo;.gcc_except_table&rdquo;</li>
<li>Unwind will try to locate a landing pad for the exception:<ul>
<li>Unwind will call the personality function with the action _UA_SEARCH_PHASE and a context pointing to the current stack frame.</li>
<li>The personality function will check if the current stack frame can handle the exception being thrown by analyzing the LSDA.</li>
<li>If the exception can be handled it will return _URC_HANDLER_FOUND.</li>
<li>If the exception can not be handled it will return _URC_CONTINUE_UNWIND and Unwind will then try the next stack frame.</li>
</ul>
</li>
<li>If no landing pad was found, the default exception handler will be called (normally std::terminate).</li>
<li>If a landing pad was found:<ul>
<li>Unwind will iterate the stack again, calling the personality function with the action _UA_CLEANUP_PHASE.</li>
<li>The personality function will check if it can handle the current exception again:</li>
<li>If this frame can&rsquo;t handle the exception it will then run a cleanup function described by the LSDA and tell Unwind to continue with the next frame (this is actually a very important step: the cleanup function will run the destructor of all the objects allocated in this stack frame!)</li>
<li>If this frame can handle the exception, don&rsquo;t run any cleanup code: tell Unwind we want to resume execution on this landing pad.</li>
</ul>
</li>
</ul>
<p>There are two important bits of information to note here:
1. Running a two-phase exception handling procedure means that in case no handler was found then the default exception handler can get the original exception&rsquo;s stack trace (if we were to unwind the stack as we go it would get no stack trace, or we would need to keep a copy of it somehow!).
2. Running a _UA_CLEANUP_PHASE and calling a second time each frame, even though we already know the frame that will handle the exception, is also really important: the personality function will take this chance to run all the destructors for objects built on this scope. It is what makes RAII an exception safe idiom!</p>
<p>Now that we understand how the catch lookup phase works we can continue our personality function implementation. The next time.</p>