<!DOCTYPE html>
<html>
<head>

<link rel="icon" href="favicon.ico" type="image/x-icon"/>
<link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
<title>C++ exceptions under the hood 18: getting the right stack frame Nico Brailovsky's blog</title>

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="/style.css">
</head>

<body>

<div id="siteheader">
<h1>Nico Brailovsky's blog</h1>

<div class="nav tabs is-full">
  <a class="is-center" href="/">Home</a>
  <a class="is-center" href="/blog/index.html">Blog</a>
  <a class="is-center"
     href="https://github.com/search?type=code&q=repo%3Anicolasbrailo%2Fnicolasbrailo.github.io%20sitesearch"
     onclick="togglesearch(); return false">Site search</a>
  <a class="is-center" href="/blog/history.html">Archive</a>
  <a class="is-center" href="/blog/series/">Series</a>
  <a class="is-center" href="/blog/projects.html">Projects</a>
  <a class="is-center" href="/blog/aboutme.html">About</a>
</div>

<div id="sitesearch" class="nav tabs is-full is-hidden">
  <form onsubmit="dosearch()">
  <input type="text" id="sitesearch_q"/>
  <input type="submit" text="Search" onclick="dosearch()" />
  </form>
</div>

</div>

<div id="content" class="language-clike">
<h2>C++ exceptions under the hood 18: getting the right stack frame</h2>

Post by Nico Brailovsky @ 2013-05-16 - <a href="/blog/2013/0516_Cexceptionsunderthehood18gettingtherightstackframe.html">Permalink</a> 

<p>Our latest personality function knows whether it can handle an exception or not (assuming there is only one catch statement per try block and assuming no inheritance is used) but to make this knowledge useful, we have first to check if the exception we can handle matches the exception being thrown. Let's try to do this.</p>
<p>Of course, we need first to know the exception type. To do this we need to save the exception type when <strong>__cxa_throw</strong> is called (this is the chance the ABI gives us to set all our custom data):</p>
<p>Note: You can download the full sourcecode for this project <a href="https://github.com/nicolasbrailo/cpp_exception_handling_abi/tree/master/abi_v09">in my github repo</a>.</p>
<pre lang="c++"><code class="language-c++" lang="c++">void __cxa_throw(void<em> thrown_exception,
                 std::type_info </em>tinfo,
                 void (<em>dest)(void</em>))
{
    __cxa_exception <em>header = ((__cxa_exception </em>) thrown_exception - 1);
    // We need to save the type info in the exception header <em>Unwind</em> will
    // receive, otherwise we won't be able to know it when unwinding
    header-&gt;exceptionType = tinfo;
    _Unwind_RaiseException(&amp;header-&gt;unwindHeader);
}
</code></pre>
<p>And now we can read the exception type in our personality function and easily check if the exception types match (the exception names are C++ strings, so doing a == is enough to check this:</p>
<pre lang="c++"><code class="language-c++" lang="c++">// Get the type of the exception we can handle
const void<em> catch_type_info = lsda.types_table_start[ -1 * type_index ];
const std::type_info </em>catch_ti = (const std::type_info <em>) catch_type_info;
// Get the type of the original exception being thrown
__cxa_exception</em> exception_header = (__cxa_exception<em>)(unwind_exception+1) - 1;
std::type_info </em>org_ex_type = exception_header-&gt;exceptionType;
printf("%s thrown, catch handles %s\n",
            org_ex_type-&gt;name(),
            catch_ti-&gt;name());
// Check if the exception being thrown is of the same type
// than the exception we can handle
if (org_ex_type-&gt;name() != catch_ti-&gt;name())
    continue;
</code></pre>
<p>Check <a href="https://github.com/nicolasbrailo/cpp_exception_handling_abi/tree/master/abi_v09">here</a> for the full source with the new changes.</p>
<p>Of course there would be a problem if we add that (can you see it?). If the exception is thrown in two phases and we said in the first one we would handle it, then we can't say on the second one we don't want it anymore. I don't know if _Unwind_ handles this case according to any documentation but this is most likely calling upon undefined behavior, so just saying we'll handle everything is no longer enough.</p>
<p>Since we gave our personality function the ability to know if the landing pad can handle the exception being thrown we have been lying to _Unwind_ about which exceptions we can handle; even though we said we handle all of them on <a href="https://github.com/nicolasbrailo/cpp_exception_handling_abi/tree/master/abi_v09">our ABI 9</a>, the truth is that we didn't know whether we would be able to handle it. That's easy to change, we can do something like this:</p>
<pre lang="c++"><code class="language-c++" lang="c++"><em>Unwind_Reason_Code __gxx_personality_v0 (...)
{
    printf("Personality function, searching for handler\n");
    // ...
    foreach (call site entry in lsda)
    {
        if (call site entry.not_good()) continue;
        // We found a landing pad for this exception; resume execution
        // If we are on search phase, tell _Unwind</em> we can handle this one
        if (actions &amp; _UA_SEARCH_PHASE) return _URC_HANDLER_FOUND;
        // If we are not on search phase then we are on _UA_CLEANUP_PHASE
        /<em> set everything so the landing pad can run </em>/
        return _URC_INSTALL_CONTEXT;
    }
    return _URC_CONTINUE_UNWIND;
}
</code></pre>
<p>As usual, check the full sourcecode for this project <a href="https://github.com/nicolasbrailo/cpp_exception_handling_abi/tree/master/abi_v10">in my github repo</a>.</p>
<p>So, what would we get if we run the personality function with this change? Fail, that's what we'd get! Remember our throwing functions? This one should catch our exception:</p>
<pre lang="c++"><code class="language-c++" lang="c++">void catchit() {
    try {
        try_but_dont_catch();
    } catch(Fake_Exception&amp;) {
        printf("Caught a Fake_Exception!\n");
    } catch(Exception&amp;) {
        printf("Caught an Exception!\n");
    }
    printf("catchit handled the exception\n");
}
</code></pre>
<p>Unfortunately, our personality function only checks for the first type the landing pad can handle. If we delete the Fake_Exception catch block and try it again, though, we'd get a different story: finally, success! Our personality function can now select the correct catch in the correct frame, provided there's no try block with multiple catches.</p>
<p>Next time we'll be further improving this.</p>

<a href="https://github.com/nicolasbrailo/nicolasbrailo.github.io/issues/new?title=Comment@md_blog/2013/0516_Cexceptionsunderthehood18gettingtherightstackframe.md&body=I%20have%20a%20comment!">Leave a comment</a>



</div>

<div id="sitefooter">
  <!-- TODO -->
</div>

<script src="/search.js"></script>
<script src="/codehighlight.js"></script>

</body>
</html>
